export {
  resolveNarrationRoot,
  narrationPlanDir,
  segmentArtifactPath,
  segmentOperationPath,
  sceneAudioArtifactPath,
  timingSnapshotPath,
  subtitleArtifactDir,
  assertSafeSegment,
  assertPathInsideRoot,
  atomicWriteJson,
  readJsonIfExists,
  sha256Bytes,
  mediaSrcForHash,
} from './narration-paths.ts';
