import type { QualificationCommandDefinitionV1 } from '../contracts/evidence-types.ts';

/** Allowlisted qualification commands only (no arbitrary shell from MCP). */
export const QUALIFICATION_COMMANDS: Record<string, QualificationCommandDefinitionV1> = {
  typescript: {
    id: 'typescript',
    executable: 'npx',
    args: ['tsc', '-b'],
    timeoutMs: 600_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'sanitized',
    secretRedaction: true,
  },
  'unit-tests': {
    id: 'unit-tests',
    npmScript: 'test',
    timeoutMs: 1_800_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  lint: {
    id: 'lint',
    npmScript: 'lint',
    timeoutMs: 600_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'sanitized',
    secretRedaction: true,
  },
  'web-build': {
    id: 'web-build',
    npmScript: 'build',
    timeoutMs: 900_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'sanitized',
    secretRedaction: true,
  },
  'm1-m2-regression': {
    id: 'm1-m2-regression',
    npmScript: 'verify:better-chat-cut-regression:assets-motion',
    timeoutMs: 2_400_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'm3-regression': {
    id: 'm3-regression',
    npmScript: 'verify:better-chat-cut-regression:scenes',
    timeoutMs: 2_400_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'm4-regression': {
    id: 'm4-regression',
    npmScript: 'verify:better-chat-cut-regression:video',
    timeoutMs: 2_400_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'm5-regression': {
    id: 'm5-regression',
    npmScript: 'verify:better-chat-cut-regression:narration-render',
    timeoutMs: 3_600_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'm6-regression': {
    id: 'm6-regression',
    npmScript: 'verify:better-chat-cut-regression:orchestration-publishing',
    timeoutMs: 3_600_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'm7a-regression': {
    id: 'm7a-regression',
    npmScript: 'verify:better-chat-cut-regression:workspace-finalization',
    timeoutMs: 3_600_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'm7b-regression': {
    id: 'm7b-regression',
    npmScript: 'verify:better-chat-cut-m7b:e2e',
    timeoutMs: 600_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'workspace-web-e2e': {
    id: 'workspace-web-e2e',
    npmScript: 'verify:better-chat-cut-workspace:e2e',
    timeoutMs: 600_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'workspace-desktop': {
    id: 'workspace-desktop',
    npmScript: 'verify:better-chat-cut-workspace:desktop',
    timeoutMs: 600_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'desktop-build',
    secretRedaction: true,
  },
  'production-orchestrator-e2e': {
    id: 'production-orchestrator-e2e',
    npmScript: 'verify:better-chat-cut-production-orchestrator:e2e',
    timeoutMs: 1_200_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'production-render-e2e': {
    id: 'production-render-e2e',
    npmScript: 'verify:better-chat-cut-production-render-bundles:render',
    timeoutMs: 1_800_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'publishing-e2e': {
    id: 'publishing-e2e',
    npmScript: 'verify:better-chat-cut-publishing:e2e',
    timeoutMs: 900_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'oauth-vault': {
    id: 'oauth-vault',
    npmScript: 'verify:better-chat-cut-connection-onboarding',
    timeoutMs: 300_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'oauth-loopback-security': {
    id: 'oauth-loopback-security',
    npmScript: 'verify:better-chat-cut-connection-onboarding:desktop',
    timeoutMs: 300_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'desktop-build',
    secretRedaction: true,
  },
  'backup-restore-e2e': {
    id: 'backup-restore-e2e',
    npmScript: 'verify:better-chat-cut-backup-restore:e2e',
    timeoutMs: 300_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'backup-restore': {
    id: 'backup-restore',
    npmScript: 'verify:better-chat-cut-backup-restore',
    timeoutMs: 300_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'desktop-security': {
    id: 'desktop-security',
    npmScript: 'verify:better-chat-cut-desktop-security',
    timeoutMs: 180_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'sanitized',
    secretRedaction: true,
  },
  'current-host-desktop-build': {
    id: 'current-host-desktop-build',
    npmScript: 'verify:better-chat-cut-desktop-distribution:current-host',
    timeoutMs: 3_600_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'desktop-build',
    secretRedaction: true,
  },
  'current-host-desktop-smoke': {
    id: 'current-host-desktop-smoke',
    npmScript: 'verify:better-chat-cut-desktop-distribution:smoke',
    timeoutMs: 600_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'desktop-build',
    secretRedaction: true,
  },
  'migration-framework': {
    id: 'migration-framework',
    npmScript: 'verify:better-chat-cut-workspace-migrations',
    timeoutMs: 300_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'upgrade-fixture': {
    id: 'upgrade-fixture',
    npmScript: 'verify:better-chat-cut-workspace-migrations',
    timeoutMs: 300_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
  'rollback-safety': {
    id: 'rollback-safety',
    npmScript: 'verify:better-chat-cut-backup-restore',
    timeoutMs: 300_000,
    workingDirectory: 'repo-root',
    environmentPolicy: 'test-isolated',
    secretRedaction: true,
  },
};

export function getQualificationCommand(id: string): QualificationCommandDefinitionV1 | undefined {
  return QUALIFICATION_COMMANDS[id];
}
